#!/usr/bin/env python3
"""Generate kernel/src/font.rs from a PSF console font.

Run once; the output is committed so the build needs no Python. This script
exists to record where the font data came from, not as a build step.

Source: /usr/share/consolefonts/Lat15-VGA16.psf.gz (Debian console-setup),
the classic IBM PC VGA 8x16 face. Debian's copyright file for that package
states "All console fonts are public domain by nature", so embedding the
bitmaps raises no licensing question.

Only printable ASCII (0x20..=0x7E) is emitted — 95 glyphs. Anything outside
that range renders as '?' at runtime.
"""
import gzip
import sys

SRC = "/usr/share/consolefonts/Lat15-VGA16.psf.gz"
FIRST, LAST = 0x20, 0x7E

data = gzip.open(SRC, "rb").read()
if data[:2] != b"\x36\x04":
    sys.exit(f"{SRC}: not a PSF1 font")

charsize = data[3]
if charsize != 16:
    sys.exit(f"expected an 8x16 font, got charsize={charsize}")
glyphs = data[4:]

rows = []
for code in range(FIRST, LAST + 1):
    off = code * charsize
    body = ", ".join(f"0x{b:02x}" for b in glyphs[off : off + charsize])
    ch = chr(code)
    label = "space" if ch == " " else ch
    rows.append(f"    // {code:#04x} {label}\n    [{body}],")

print(f"generated {len(rows)} glyphs", file=sys.stderr)

with open("kernel/src/font.rs", "w") as f:
    f.write(f'''//! An 8x16 bitmap font.
//!
//! GENERATED by `tools/generate_font.py` from
//! `{SRC}` — do not edit by hand.
//!
//! Each glyph is {charsize} bytes, one per scanline, most significant bit
//! leftmost. Only printable ASCII ({FIRST:#04x}..={LAST:#04x}) is stored;
//! [`glyph`] substitutes `?` for anything else.

/// Width of a glyph in pixels. One byte per scanline, so this is 8.
pub const GLYPH_WIDTH: usize = 8;
/// Height of a glyph in pixels.
pub const GLYPH_HEIGHT: usize = {charsize};

const FIRST: u8 = {FIRST:#04x};
const LAST: u8 = {LAST:#04x};

static GLYPHS: [[u8; GLYPH_HEIGHT]; {len(rows)}] = [
{chr(10).join(rows)}
];

/// The bitmap for `byte`, or the bitmap for `?` if it is not printable.
pub fn glyph(byte: u8) -> &'static [u8; GLYPH_HEIGHT] {{
    let index = if (FIRST..=LAST).contains(&byte) {{
        (byte - FIRST) as usize
    }} else {{
        (b'?' - FIRST) as usize
    }};
    &GLYPHS[index]
}}
''')
